#! /bin/bash

token="$(cat $HOME/bot-token)"
chat_id="$(cat $HOME/bot-target)"
message=$1
url="https://api.telegram.org/bot$token/sendMessage"

curl -s -X POST $url -d chat_id=$chat_id -d text="$message"
